[package]
name = "streamline"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0"
sha2 = "0.10"
hex = "0.4"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
